### PR TITLE
Updated foxy install script and README

### PR DESCRIPTION
**Pull request by AVSurfer123**
Updated foxy install to use vcs import before rosdep. Updated README with better instructions

### CODE REVIEW

**Review by Michael-Equi — CHANGES_REQUESTED** [review]
Can we add automatic shell type checking to the foxy script so it can be compatible with both bash and zsh?

**Comment by AVSurfer123** [comment]
Hmm probably. I've never used zsh before though. I think we can use the `$SHELL` variable to do this. What is the config file for zsh, `~/.zshrc`?

**Comment by Michael-Equi** [comment]
> Hmm probably. I've never used zsh before though. I think we can use the `$SHELL` variable to do this. What is the config file for zsh, `~/.zshrc`?

~/.zshrc is right.

**Review by williamlooo — APPROVED** [review]

**Review by Michael-Equi — CHANGES_REQUESTED** [review]
Any .bash extension needs to be changes to .zsh

**Review by Michael-Equi — APPROVED** [review]

**Pull request merged**
